import type { Metadata } from "next";
import { projects } from "@/data/projects";
import { titleCase } from "@/lib/text";

export const siteUrl = "https://oyoto.co.uk";
export const siteName = "Oyoto";
/** The wordmark as it appears on the page; search engines get both spellings. */
export const brandName = "Oyotō";
export const siteTagline = "Web, mobile and AI product studio";
export const siteDescription =
  "Oyoto is a UK digital product studio founded by software engineer James Mboma, designing and building web platforms, mobile apps, AI integrations and cloud systems.";
export const founderName = "James Mboma";
export const contactEmail = "oyotostudios@outlook.com";
export const contactMailto = `mailto:${contactEmail}?subject=${encodeURIComponent(
  "Project enquiry for Oyoto"
)}&body=${encodeURIComponent(`Hi Oyoto Team,

I'm interested in working with Oyoto.

Name:
Company / project:
Website or socials:

What are you looking to build?

What stage is the project at?

Ideal timeline:
Budget range:

Anything else I should know?

Thanks,`)}`;
/** Generated by app/opengraph-image.tsx. */
export const defaultOgImage = "/opengraph-image";
const defaultOgCard = {
  url: defaultOgImage,
  width: 1200,
  height: 630,
  alt: `${siteName}, a UK studio building web, mobile and AI products`,
};
export const defaultCalLink = "james-mboma-kzbj0s/30min";

export const socialLinks = [
  "https://github.com/mboma99",
  "https://www.linkedin.com/in/james-mboma/",
];

export const serviceAreas = [
  "Full-stack development",
  "Cloud architecture",
  "UI/UX engineering",
  "AI integration",
  "Mobile apps",
  "Business intelligence",
  "Technical consulting",
];

type JsonLdValue =
  | string
  | number
  | boolean
  | null
  | JsonLdValue[]
  | { [key: string]: JsonLdValue };

export function absoluteUrl(path = "/") {
  return new URL(path, siteUrl).toString();
}

export function createMetadata({
  title,
  description,
  path = "/",
  type = "website",
}: {
  /** Page title without the brand; the root template appends it. */
  title?: string;
  description: string;
  path?: string;
  type?: "website" | "article";
}): Metadata {
  const url = absoluteUrl(path);
  // The title template only reaches <title>, so share cards get the brand here.
  const shareTitle = title ? `${title} | ${siteName}` : `${siteName} | ${siteTagline}`;

  return {
    // An object title keeps the brand template alive for nested segments; a
    // plain string here would drop "| Oyoto" from every page below it.
    ...(title ? { title: { default: title, template: `%s | ${siteName}` } } : {}),
    description,
    alternates: {
      canonical: url,
    },
    openGraph: {
      title: shareTitle,
      description,
      url,
      siteName,
      locale: "en_GB",
      type,
      // Setting openGraph replaces the parent's, so the default card is
      // restated here. A nearer opengraph-image file still takes precedence.
      images: [defaultOgCard],
    },
    twitter: {
      card: "summary_large_image",
      title: shareTitle,
      description,
    },
  };
}

export function jsonLdScript(data: JsonLdValue) {
  return {
    type: "application/ld+json",
    dangerouslySetInnerHTML: {
      __html: JSON.stringify(data).replace(/</g, "\\u003c"),
    },
  };
}

export function projectUrl(slug: string) {
  return absoluteUrl(`/projects/${slug}`);
}

export function getProjectBySlug(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export function projectJsonLd(slug: string): JsonLdValue | null {
  const project = getProjectBySlug(slug);

  if (!project) {
    return null;
  }

  return {
    "@context": "https://schema.org",
    "@type": "CreativeWork",
    "@id": `${projectUrl(project.slug)}#case-study`,
    name: titleCase(project.title),
    headline: `${titleCase(project.title)} case study`,
    description: project.description,
    url: projectUrl(project.slug),
    image: absoluteUrl(project.image),
    dateCreated: project.year,
    creator: {
      "@id": `${siteUrl}/#organization`,
    },
    about: project.tags,
    keywords: project.caseStudy.techStack,
    text: [
      project.caseStudy.overview,
      project.caseStudy.challenge,
      project.caseStudy.solution,
      project.caseStudy.outcome,
    ].join(" "),
    isPartOf: {
      "@id": `${siteUrl}/#website`,
    },
  };
}

export function projectBreadcrumbJsonLd(slug: string): JsonLdValue | null {
  const project = getProjectBySlug(slug);

  if (!project) {
    return null;
  }

  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: absoluteUrl("/") },
      { "@type": "ListItem", position: 2, name: "Projects", item: absoluteUrl("/projects") },
      {
        "@type": "ListItem",
        position: 3,
        name: titleCase(project.title),
        item: projectUrl(project.slug),
      },
    ],
  };
}

/** The case studies as an ordered list, for the home and projects pages. */
export function projectListJsonLd(): JsonLdValue {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "Selected work",
    itemListElement: projects.map((project, i) => ({
      "@type": "ListItem",
      position: i + 1,
      url: projectUrl(project.slug),
      name: titleCase(project.title),
    })),
  };
}

export function siteJsonLd(): JsonLdValue {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${siteUrl}/#organization`,
        name: siteName,
        alternateName: [brandName, "Oyoto Studios"],
        description: siteDescription,
        url: siteUrl,
        logo: absoluteUrl("/icon.svg"),
        image: absoluteUrl(defaultOgImage),
        email: contactEmail,
        areaServed: "GB",
        founder: {
          "@id": `${siteUrl}/#person`,
        },
        sameAs: socialLinks,
        knowsAbout: serviceAreas,
        makesOffer: serviceAreas.map((service) => ({
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            name: service,
          },
        })),
      },
      {
        "@type": "Person",
        "@id": `${siteUrl}/#person`,
        name: founderName,
        jobTitle: "Software Engineer",
        url: siteUrl,
        email: contactEmail,
        sameAs: socialLinks,
        worksFor: {
          "@id": `${siteUrl}/#organization`,
        },
        knowsAbout: serviceAreas,
      },
      {
        "@type": "WebSite",
        "@id": `${siteUrl}/#website`,
        name: siteName,
        alternateName: brandName,
        description: siteDescription,
        url: siteUrl,
        publisher: {
          "@id": `${siteUrl}/#organization`,
        },
        inLanguage: "en-GB",
      },
    ],
  };
}
